"""added qrcode_url attribute to AccessControl

Revision ID: 2a6c99bdc0ca
Revises: 7287c466d72e
Create Date: 2024-10-10 23:43:14.943540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6c99bdc0ca'
down_revision = '7287c466d72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_control', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qrcode_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.drop_column('qrcode_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qrcode_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('access_control', schema=None) as batch_op:
        batch_op.drop_column('qrcode_url')

    # ### end Alembic commands ###
