"""added association object between health records and access controls

Revision ID: 7287c466d72e
Revises: f18e56623af6
Create Date: 2024-10-10 20:56:32.676907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7287c466d72e'
down_revision = 'f18e56623af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_record_access_control',
    sa.Column('hr_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('ac_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ac_id'], ['access_control.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hr_id'], ['health_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hr_id', 'ac_id')
    )
    with op.batch_alter_table('access_control', schema=None) as batch_op:
        batch_op.alter_column('doc_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_control', schema=None) as batch_op:
        batch_op.alter_column('doc_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('health_record_access_control')
    # ### end Alembic commands ###
