"""location based fields for user

Revision ID: 85e161a3da81
Revises: b98e0b1902f1
Create Date: 2024-12-19 00:44:49.181354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e161a3da81'
down_revision = 'b98e0b1902f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pincode')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
