"""adjustment to serve static files from directory

Revision ID: b689fbde19c8
Revises: 85e161a3da81
Create Date: 2024-12-27 21:52:18.017506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b689fbde19c8'
down_revision = '85e161a3da81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('health_records_file_url_key', type_='unique')
        batch_op.create_unique_constraint(None, ['file_name'])
        batch_op.drop_column('file_url')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('avatar_path')

    with op.batch_alter_table('health_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('health_records_file_url_key', ['file_url'])
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
