"""shifted from enum to string for user role

Revision ID: d2f2ca493053
Revises: 2a6c99bdc0ca
Create Date: 2024-10-14 00:02:02.511532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2f2ca493053'
down_revision = '2a6c99bdc0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('DOCTOR', 'PATIENT', name='userrole'),
               type_=sa.String(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=7),
               type_=postgresql.ENUM('DOCTOR', 'PATIENT', name='userrole'),
               existing_nullable=False)

    # ### end Alembic commands ###
