"""paginatedmixin and dictmixin

Revision ID: f18e56623af6
Revises: f0f7f624f50c
Create Date: 2024-10-09 00:38:07.763736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18e56623af6'
down_revision = 'f0f7f624f50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_control', schema=None) as batch_op:
        batch_op.drop_index('ix_access_control_hr_id')
        batch_op.drop_constraint('access_control_hr_id_fkey', type_='foreignkey')
        batch_op.drop_column('hr_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_control', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hr_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('access_control_hr_id_fkey', 'health_records', ['hr_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('ix_access_control_hr_id', ['hr_id'], unique=False)

    # ### end Alembic commands ###
